=== ToureNPlaner/mapsforge-fork/mapsforge-routing/src/org/mapsforge/routing/preprocessing/graph/config.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="config">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="routingTags" type="routingTagsType"
					minOccurs="1" maxOccurs="1">
					<xsd:annotation>
						<xsd:documentation>
							This routingTags element is for all the
							additional tags you need
							for your routing graph. e.g.
							&lt;tag
							k=name v=* /&gt; </xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="vehicles" type="vehiclesType"
					minOccurs="1" maxOccurs="1"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="vehiclesType">
		<xsd:annotation>
			<xsd:documentation></xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="vehicle" type="vehicleType" minOccurs="1"
				maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>Element for a new vehicle (you can build the
						routing graph exactly for this vehicle)</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="vehicleType">
		<xsd:annotation>
			<xsd:documentation>Defines a vehicle with name, maxspeed, the ways it
				can drive, restrictions(traffic signs etc.) and factors which
				influence the weight of the routing graph.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" minOccurs="1"
				maxOccurs="1" />
			<xsd:element name="maxspeed" type="xsd:int" minOccurs="1"
				maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Maxspeed in km/h</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<!-- all allowed ways (key - value) -->
			<xsd:element name="usableWayTags" type="highwayTagsType"
				minOccurs="1" maxOccurs="1" />
			<!-- tags which influence the weight of an edge (key - value) -->
			<xsd:element name="restrictions" type="restrictionsType"
				minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Restrictions can be tags in nodes or ways or
						occure in form of relations.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="weightFactors" type="weightFactorsType"
				minOccurs="1" maxOccurs="1">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="highwayTagsType">
		<xsd:annotation>
			<xsd:documentation>Put in all the allowed highway tags with an
				addition speed specification for your vehicle.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="tag" type="highwayTagType" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="tagType">
		<xsd:annotation>
			<xsd:documentation>
				The tagType has exactly the same form as a tag in OSM(
				<!-- <tag k=* v=* /> -->
				)
			</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="k" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="v" type="xsd:string"></xsd:attribute>
	</xsd:complexType>



	<xsd:complexType name="weightFactorsType">
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="stopNodeTags" type="stopTagsType"
				minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Usually node tags which represent a stop.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="speedreductions" type="speedreductionTagsType"
				minOccurs="1" maxOccurs="1">
			</xsd:element>
			<xsd:element name="noOSMTags" type="tagsType" minOccurs="1"
				maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Other information to weight the routing graph.
						The tags don't have to be the same tags as in OSM or don't have to
						be out of the namespace of OSM!</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="stopTagsType">
		<xsd:annotation>
			<xsd:documentation>Put in tags which could stop the vehicle (e.g.
				stop signs or traffic lights).
				The tags need an additional time
				attribute which define the estimated
				stop time for forced stops (e.g.
				stop sign) and the expected
				standing time (time * probability to
				stand) for conditional stops
				like traffic lights.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="tag" type="tagTypeWithTime" minOccurs="0"
				maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="tagTypeWithTime">
		<xsd:annotation>
			<xsd:documentation>Simple tag with an additional time attribute in
				seconds.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="tagType">
				<xsd:attribute name="time" type="xsd:int" use="required"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="speedreductionTagsType">
		<xsd:annotation>
			<xsd:documentation>Put in all the tags which could slow down your
				vehicle either as the wayTags element(longer speed reduction) or as
				a
				nodeTags element (few and far between reductions).
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="wayTags" type="tagsWithPercType"
				minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>
						Put in the tags for a longer speed reductions,
						e.g. surface types,
						represented as a way. Needs
						to have speed reduction mentioned as a
						percentage value. (e.g. 30 is allowed, we'll go
						down to 15 so the
						percentage value should be 50)
						E.g. Put in the the suface tag as:
						<!-- <tag k="surface" v="gravel" perc="5" /> -->
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="nodeTags" type="tagsWithPercType"
				minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>
						Put in few and far between reduction tags like
						traffic calming elements. Need to have speed
						reduction mentioned as
						a percentage value. (e.g.
						30 is allowed, we'll go down to 15 so the
						percentage value should be 50)
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="dynamicWayTags" type="tagsType"
				minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>This element is for dynamic valued way tags(no fixed
						value 'v', only key 'k') like maxspeed or incline.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="percType">
		<xsd:restriction base="xsd:int">
			<xsd:minInclusive value="0"></xsd:minInclusive>
			<xsd:maxInclusive value="100"></xsd:maxInclusive>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="tagTypeWithPerc">
		<xsd:annotation>
			<xsd:documentation>Simple tag with optional percentage attribute.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="tagType">
				<xsd:attribute name="percent" type="percType" use="required">
					<xsd:annotation>
						<xsd:documentation>please put in all additional tags you need for
							your routing algorithm</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="highwayTagType">
		<xsd:annotation>
			<xsd:documentation>Normal tag with an additional speed attribute.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="tagType">
				<xsd:attribute name="speed" type="xsd:int" use="required"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>




	<xsd:complexType name="restrictionsType">
		<xsd:annotation>
			<xsd:documentation>Restrictiocs can be tags in nodes or ways but can
				also be relations.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="wayTags" type="tagsType" minOccurs="1"
				maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Put in restriction tags (e.g. traffic signs)
						where
						the vehilce isn't suppose to drive/go.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="relations" type="relationType"
				minOccurs="1" maxOccurs="1"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="relationType">
		<xsd:annotation>
			<xsd:documentation>Put in the tags and members of the relation which
				should be considered.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence maxOccurs="unbounded" minOccurs="0">
			<xsd:element name="tag" type="tagType" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="member" type="memberType" minOccurs="0"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="memberType">
		<xsd:attribute name="type" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="way" />
					<xsd:enumeration value="node" />
					<xsd:enumeration value="relation" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="ref" type="xsd:string" />
		<xsd:attribute name="role" type="xsd:string" />
	</xsd:complexType>


	<xsd:complexType name="routingTagsType">
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="wayTags" type="tagsType" minOccurs="1"
				maxOccurs="1"></xsd:element>
			<xsd:element name="nodeTags" type="tagsType" minOccurs="1"
				maxOccurs="1"></xsd:element>
			<xsd:element name="relationTags" type="tagsType"
				minOccurs="1" maxOccurs="1"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="tagsType">
		<xsd:annotation>
			<xsd:documentation>A simple list of tags.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="tag" type="tagType" minOccurs="0"
				maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="tagsWithPercType">
		<xsd:sequence>
			<xsd:element name="tag" type="tagTypeWithPerc" minOccurs="0"
				maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== ToureNPlaner/mapsforge-fork/mapsforge-routing/src/org/mapsforge/routing/preprocessing/graph/config.xml
<?xml version="1.0" encoding="utf-8" ?>


<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="config.xsd">
	<routingTags>
		<wayTags>
			<tag k="name" />
			<tag k="junction" v="roundabout" />
		</wayTags>
		<nodeTags>
		</nodeTags>
		<relationTags>
		</relationTags>
	</routingTags>
	<vehicles>
		<!-- new Vehicle -->
		<vehicle>
			<name>motorcar</name>
			<maxspeed>130</maxspeed>
			<!-- all allowed ways (key - value) -->
			<usableWayTags>
				<tag v="motorway" k="highway" speed="130" />
				<tag v="motorway_link" k="highway" speed="80" />
				<tag v="trunk" k="highway" speed="120" />
				<tag v="trunk_link" k="highway" speed="80" />
				<tag v="primary" k="highway" speed="130" />
				<tag v="primary_link" k="highway" speed="80" />
				<tag v="secondary" k="highway" speed="100" />
				<tag v="secondary_link" k="highway" speed="80" />
				<tag v="tertiary" k="highway" speed="50" />
				<tag v="unclassified" k="highway" speed="50" />
				<tag v="road" k="highway" speed="50" />
				<tag v="residential" k="highway" speed="50" />
				<tag v="living_street" k="highway" speed="10" />
				<tag v="track" k="highway" speed="50" />
			</usableWayTags>
			<restrictions>
				<wayTags>
					<tag k="motorcar" v="no" />
					<tag k="vehicle" v="no" />
					<tag k="access" v="no" />
					<tag k="access" v="agricultural" />
					<tag k="access" v="delivery" />
					<tag k="access" v="private" />
					<tag k="motorcar" v="agricultural" />
					<tag k="motorcar" v="delivery" />
					<tag k="motorcar" v="private" />
					<tag k="vehicle" v="agricultural" />
					<tag k="vehicle" v="delivery" />
					<tag k="vehicle" v="private" />
					<tag k="motor_vehicle" v="agricultural" />
					<tag k="motor_vehicle" v="delivery" />
					<tag k="motor_vehicle" v="private" />
				</wayTags>
				<relations>
					<tag k="type" v="restriction" />
					<tag k="restriction" v="no_left_turn" />
					<tag k="restriction" v="no_right_turn" />
					<tag k="restriction" v="no_straight_on" />
					<tag k="restriction" v="only_left_turn" />
					<tag k="restriction" v="only_right_turn" />
					<tag k="restriction" v="only_straight_on" />
					<member type="node" role="via" />
					<member type="way" role="from" />
					<member type="way" role="to" />
				</relations>
			</restrictions>
			<weightFactors>
				<stopNodeTags>
					<!-- conditional stops, with an expected time value -->
					<tag k="highway" v="traffic_signal" time="90" />
					<tag k="highway" v="give_way" time="45" />
					<tag k="railway" v="level_crossing" time="120" />
					<tag k="highway" v="crossing" time="20" />
					<tag k="junction" v="roundabout" time="10" />
					<tag k="highway" v="mini_roundabout" time="5" />
					<!-- predictable stops -->
					<tag k="highway" v="stop" time="30" />
					<tag k="barrier" v="toll_booth" time="300" />
				</stopNodeTags>
				<speedreductions>
					<!-- speedreductions over a longer distance -->
					<wayTags>

						<tag k="tracktype" v="grade2" percent="10" />
						<tag k="tracktype" v="grade3" percent="20" />
						<tag k="tracktype" v="grade4" percent="50" />
						<tag k="tracktype" v="grade5" percent="80" />
						<tag k="surface" v="unpaved" percent="30" />
						<tag k="suface" v="gravel" percent="30" />
						<tag k="surface" v="compacted" percent="20" />
						<tag k="surface" v="pebblestone" percent="30" />
						<tag k="surface" v="sand" percent="40" />
						<tag k="surface" v="dirt" percent="60" />
						<tag k="surface" v="mud" percent="70" />
					</wayTags>
					<nodeTags>
						<!-- speedreductions over a short distance, e.g. 10m -20 m -->
						<tag k="highway" v="speed_camera" percent="20" />
						<tag k="traffic_calming" v="yes" percent="50" />
						<tag k="traffic_calming" v="bump" percent="50" />
						<tag k="traffic_calming" v="chicane" percent="30" />
						<tag k="traffic_calming" v="cushion" percent="50" />
						<tag k="traffic_calming" v="hump" percent="50" />
						<tag k="traffic_calming" v="rumble_strip" percent="10" />
					</nodeTags>
					<dynamicWayTags>
						<tag k="maxspeed" />
					</dynamicWayTags>
				</speedreductions>
				<!-- ATTENTION: the following tags don't exist in OSM !!! -->
				<noOSMTags>
					<!-- time for turning left and right -->
					<tag k="right_turn" v="30" />
					<tag k="left_turn" v="60" />
				</noOSMTags>
			</weightFactors>
		</vehicle>
		<vehicle>
			<name>bicycle</name>
			<maxspeed>30</maxspeed>
			<usableWayTags>
				<tag v="primary" k="highway" speed="30" />
				<tag v="primary_link" k="highway" speed="30" />
				<tag v="secondary" k="highway" speed="20" />
				<tag v="secondary_link" k="highway" speed="20" />
				<tag v="tertiary" k="highway" speed="20" />
				<tag v="unclassified" k="highway" speed="20" />
				<tag v="road" k="highway" speed="20" />
				<tag v="residential" k="highway" speed="20" />
				<tag v="living_street" k="highway" speed="10" />
				<tag v="track" k="highway" speed="15" />
				<tag v="path" k="highway" speed="15" />
				<tag v="cycleway" k="highway" speed="30" />
			</usableWayTags>
			<restrictions>
				<wayTags>
					<tag k="access" v="no" />
					<tag k="access" v="private" />
					<tag k="bicycle" v="no" />
				</wayTags>
				<relations>

				</relations>
			</restrictions>
			<weightFactors>
				<stopNodeTags>
					<tag k="highway" v="traffic_signal" time="90" />
					<tag k="highway" v="give_way" time="45" />
					<tag k="railway" v="level_crossing" time="120" />
					<tag k="highway" v="crossing" time="20" />
					<tag k="junction" v="roundabout" time="10" />
				</stopNodeTags>
				<speedreductions>
					<wayTags>
						<tag k="suface" v="gravel" percent="30" />
						<tag k="surface" v="cobblestone" percent="30" />
						<tag k="surface" v="compacted" percent="20" />
						<tag k="surface" v="pebblestone" percent="30" />
						<tag k="surface" v="sand" percent="40" />
						<tag k="surface" v="dirt" percent="60" />
						<tag k="surface" v="mud" percent="70" />
						<tag k="tracktype" v="grade2" percent="10" />
						<tag k="tracktype" v="grade3" percent="20" />
						<tag k="tracktype" v="grade4" percent="50" />
						<tag k="tracktype" v="grade5" percent="80" />
					</wayTags>
					<nodeTags>
						<tag k="traffic_calming" v="yes" percent="50" />
						<tag k="traffic_calming" v="bump" percent="50" />
						<tag k="traffic_calming" v="hump" percent="50" />
						<tag k="traffic_calming" v="rumble_strip" percent="10" />
					</nodeTags>
					<dynamicWayTags>
						<tag k="incline" />
						<tag k="maxspeed" />
					</dynamicWayTags>
				</speedreductions>
				<noOSMTags>
					<!-- time for turning left and right -->
					<tag k="right_turn" v="30" />
					<tag k="left_turn" v="60" />
				</noOSMTags>
			</weightFactors>
		</vehicle>
		<vehicle>
			<name>foot</name>
			<maxspeed>10</maxspeed>
			<usableWayTags>
				<tag v="secondary" k="highway" speed="5" />
				<tag v="secondary_link" k="highway" speed="5" />
				<tag v="tertiary" k="highway" speed="5" />
				<tag v="unclassified" k="highway" speed="5" />
				<tag v="road" k="highway" speed="5" />
				<tag v="residential" k="highway" speed="5" />
				<tag v="living_street" k="highway" speed="5" />
				<tag v="track" k="highway" speed="5" />
				<tag v="path" k="highway" speed="5" />
				<tag v="cycleway" k="highway" speed="5" />
				<tag v="pedestrian" k="highway" speed="5" />
				<tag v="footway" k="highway" speed="5" />
			</usableWayTags>
			<restrictions>
				<wayTags>
					<tag k="foot" v="no" />
				</wayTags>
				<relations>
				</relations>
			</restrictions>
			<weightFactors>
				<stopNodeTags>
					<!-- would be considered even when no road is crossed -->
					<!-- <tag k="highway" v="traffic_signal" time="90" /> -->
					<tag k="railway" v="crossing" time="120" />
					<!-- would be considered even when no road is crossed -->
					<!-- <tag k="highway" v="crossing" time="20" /> -->
				</stopNodeTags>
				<speedreductions>
					<wayTags></wayTags>
					<nodeTags></nodeTags>
					<dynamicWayTags></dynamicWayTags>
				</speedreductions>
				<noOSMTags></noOSMTags>
			</weightFactors>
		</vehicle>

	</vehicles>
</config>
